import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(280, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_plain_text = QtWidgets.QLabel(self.centralwidget)
        self.label_plain_text.setGeometry(QtCore.QRect(50, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_plain_text.setFont(font)
        self.label_plain_text.setObjectName("label_plain_text")
        self.txt_plain_textext = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_textext.setGeometry(QtCore.QRect(160, 90, 591, 141))
        self.txt_plain_textext.setObjectName("txt_plain_textext")
        self.label_plain_text_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_plain_text_2.setGeometry(QtCore.QRect(50, 250, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_plain_text_2.setFont(font)
        self.label_plain_text_2.setObjectName("label_plain_text_2")
        self.label_cipher_text = QtWidgets.QLabel(self.centralwidget)
        self.label_cipher_text.setGeometry(QtCore.QRect(50, 300, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_cipher_text.setFont(font)
        self.label_cipher_text.setObjectName("label_cipher_text")
        self.txt_key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(160, 250, 591, 31))
        self.txt_key.setObjectName("txt_key")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(160, 300, 591, 141))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(220, 480, 81, 31))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(600, 480, 81, 31))
        self.btn_decrypt.setObjectName("btn_decrypt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.label_plain_text.setText(_translate("MainWindow", "Plain text:"))
        self.label_plain_text_2.setText(_translate("MainWindow", "Key:"))
        self.label_cipher_text.setText(_translate("MainWindow", "Cipher Text:"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
